Name: gateway
Host: localhost
Port: 8888
Upstreams:
  - Grpc:
      Etcd:
        Hosts:
          - localhost:2379
        Key: hello.rpc
    # protoset mode
    ProtoSet: hello.pb
    # Mapping is optional, auto mapping from annotations (google.api.http)
    Mapping:
      - Method: get
        Path: /pingHello/:ping
        RpcPath: hello.Hello/Ping
  - Grpc:
      Endpoints:
        - localhost:8081
    # no protoset, reflection mode
    # remember to enable reflection in server side
    Mapping:
      - Method: post
        Path: /pingWorld
        RpcPath: world.World/Ping
